#!/bin/bash
# Example commands for training with new features

echo "=========================================="
echo "Training Examples with New Features"
echo "=========================================="
echo ""

echo "1. Basic training with best model tracking"
echo "-------------------------------------------"
echo "python train.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --use_wandb \\"
echo "  --save_best_model \\"
echo "  --best_metric rmse \\"
echo "  --experiment_name baseline_best"
echo ""

echo "2. Training with sequence holdout (single sequence)"
echo "----------------------------------------------------"
echo "python train.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --sequence_holdout \\"
echo "  --holdout_test_seq Salle_Chevalier \\"
echo "  --experiment_name holdout_salle"
echo ""

echo "3. Full overfitting check (RECOMMENDED)"
echo "----------------------------------------"
echo "python train.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --use_wandb \\"
echo "  --save_best_model \\"
echo "  --best_metric rmse \\"
echo "  --sequence_holdout \\"
echo "  --holdout_test_seq Salle_Chevalier \\"
echo "  --holdout_eval_seq 3rd_Floor_Luxembourg \\"
echo "  --batch_size 256 \\"
echo "  --learning_rate 0.002 \\"
echo "  --experiment_name full_overfitting_check"
echo ""

echo "4. With custom loss weights and holdout"
echo "----------------------------------------"
echo "python train.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --use_wandb \\"
echo "  --save_best_model \\"
echo "  --sequence_holdout \\"
echo "  --holdout_test_seq Salle_Chevalier \\"
echo "  --l1_weight 0.8 \\"
echo "  --silog_weight 0.2 \\"
echo "  --audio_format mel_spectrogram \\"
echo "  --experiment_name custom_loss_holdout"
echo ""

echo "5. Minimal quick test (no W&B, just holdout)"
echo "---------------------------------------------"
echo "python train.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --sequence_holdout \\"
echo "  --holdout_test_seq Salle_Chevalier \\"
echo "  --batch_size 32 \\"
echo "  --experiment_name quick_test"
echo ""

echo "=========================================="
echo "Available Sequences for Holdout:"
echo "=========================================="
echo "- Salle_Chevalier (recommended)"
echo "- 3rd_Floor_Luxembourg (recommended)"
echo "- 2ndFloorLuxembourg"
echo "- Attic"
echo "- Outdoor_Cobblestone_Path"
echo "- Salle_des_Colonnes"
echo "- V119_Cake_Corridors"
echo ""

echo "=========================================="
echo "Best Metric Options:"
echo "=========================================="
echo "- rmse (default, lower is better)"
echo "- abs_rel (lower is better)"
echo "- delta1 (higher is better)"
echo "- mae (lower is better)"
echo "- loss (lower is better)"
echo ""

echo "=========================================="
echo "Quick Start:"
echo "=========================================="
echo "# For production training with overfitting check:"
echo "python train.py --use_wandb --save_best_model --sequence_holdout --holdout_test_seq Salle_Chevalier"
echo ""
echo "# Check results in W&B:"
echo "# - val/rmse vs holdout_test/rmse"
echo "# - best_model_epoch"
echo "# - Load best model from: ./checkpoints/{experiment_name}/best_model.pth"
echo ""


