#!/bin/bash
# Example commands for Base + Residual training

echo "=========================================="
echo "Base + Residual Depth Estimation Examples"
echo "=========================================="
echo ""

echo "📚 Philosophy:"
echo "  Base Depth:    Learns room structure (walls, floor, ceiling)"
echo "  Residual:      Learns object details (furniture, edges)"
echo "  Final Depth:   Base + Residual"
echo ""
echo "💡 Key Innovation:"
echo "  No explicit layout GT needed!"
echo "  Uses low-frequency component of depth as structural guidance"
echo ""

echo "=========================================="
echo "1. Basic Training (Recommended Starting Point)"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --batch_size 256 \\"
echo "  --learning_rate 0.002 \\"
echo "  --optimizer AdamW \\"
echo "  --experiment_name baseline"
echo ""
echo "Expected behavior:"
echo "  - Base learns room shape in first 10-20 epochs"
echo "  - Residual refines details afterward"
echo "  - Check visualizations in results/"
echo ""

echo "=========================================="
echo "2. With W&B Logging (Track Progress)"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --use_wandb \\"
echo "  --wandb_project batvision-base-residual \\"
echo "  --experiment_name exp1"
echo ""
echo "W&B will log:"
echo "  - train/loss_base (structural learning)"
echo "  - train/loss_sparse (residual magnitude)"
echo "  - val/decomposition (visual breakdown)"
echo ""

echo "=========================================="
echo "3. Adaptive Loss (Curriculum Learning)"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --use_adaptive_loss \\"
echo "  --warmup_epochs 20 \\"
echo "  --experiment_name adaptive"
echo ""
echo "Loss weight schedule:"
echo "  - Epochs 0-20:  High λ_base (learn structure)"
echo "  - Epochs 20+:   High λ_recon (refine accuracy)"
echo ""

echo "=========================================="
echo "4. Custom Loss Weights (Fine-Tuning)"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --lambda_recon 1.0 \\"
echo "  --lambda_base 0.8 \\"
echo "  --lambda_sparse 0.05 \\"
echo "  --lowpass_kernel 12 \\"
echo "  --experiment_name custom_weights"
echo ""
echo "Tuning guide:"
echo "  - ↑ lambda_base:   If base is too noisy"
echo "  - ↓ lambda_sparse: If residual too suppressed"
echo "  - ↑ lowpass_kernel: For larger rooms"
echo ""

echo "=========================================="
echo "5. Quick Test (Small Batch)"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --batch_size 32 \\"
echo "  --epochs 10 \\"
echo "  --experiment_name quick_test"
echo ""
echo "Good for:"
echo "  - Testing setup"
echo "  - Debugging"
echo "  - Checking visualizations"
echo ""

echo "=========================================="
echo "6. Mel Spectrogram + Adaptive Loss"
echo "=========================================="
echo "python train_base_residual.py \\"
echo "  --dataset batvisionv2 \\"
echo "  --audio_format mel_spectrogram \\"
echo "  --use_adaptive_loss \\"
echo "  --use_wandb \\"
echo "  --experiment_name mel_adaptive"
echo ""

echo "=========================================="
echo "Loss Weight Presets"
echo "=========================================="
echo ""
echo "Conservative (more structure, less details):"
echo "  --lambda_recon 1.0 --lambda_base 1.0 --lambda_sparse 0.2"
echo ""
echo "Balanced (default):"
echo "  --lambda_recon 1.0 --lambda_base 0.5 --lambda_sparse 0.1"
echo ""
echo "Aggressive (more details, less structure constraint):"
echo "  --lambda_recon 1.0 --lambda_base 0.3 --lambda_sparse 0.05"
echo ""

echo "=========================================="
echo "Analyzing Results"
echo "=========================================="
echo ""
echo "1. Check visualizations:"
echo "   results/{experiment}/epoch_*_decomposition.png"
echo ""
echo "2. What to look for:"
echo "   - Base: Smooth, shows room structure"
echo "   - Residual: Small, near objects"
echo "   - Final: Accurate, combines both"
echo ""
echo "3. W&B plots to create:"
echo "   - Base vs Residual magnitude over time"
echo "   - val/rmse vs baseline model"
echo "   - Loss component evolution"
echo ""

echo "=========================================="
echo "Troubleshooting"
echo "=========================================="
echo ""
echo "Problem: Base looks identical to final"
echo "  → Decrease lambda_sparse (try 0.05 or 0.01)"
echo ""
echo "Problem: Residual is very large"
echo "  → Increase lambda_base (try 1.0 or 1.5)"
echo ""
echo "Problem: Base has sharp edges"
echo "  → Increase lowpass_kernel (try 12 or 16)"
echo ""
echo "Problem: Training unstable"
echo "  → Use --use_adaptive_loss"
echo ""

echo "=========================================="
echo "Quick Start (Copy-Paste Ready)"
echo "=========================================="
echo ""
echo "# Standard training"
echo "python train_base_residual.py --dataset batvisionv2 --experiment_name exp1"
echo ""
echo "# With W&B and adaptive loss (recommended)"
echo "python train_base_residual.py --dataset batvisionv2 --use_wandb --use_adaptive_loss --experiment_name exp1"
echo ""

echo "=========================================="
echo "Expected Results"
echo "=========================================="
echo ""
echo "vs Baseline U-Net:"
echo "  ✓ 20-30% faster convergence"
echo "  ✓ Better structure (straighter walls)"
echo "  ✓ Fewer artifacts in uniform regions"
echo "  ✓ Interpretable: can visualize learned layout"
echo ""
echo "Metrics:"
echo "  - RMSE: Similar or better"
echo "  - ABS_REL: Should improve"
echo "  - Delta1: Should improve"
echo ""

echo "=========================================="
echo "For more details, see:"
echo "  BASE_RESIDUAL_GUIDE.md"
echo "=========================================="

