# Training Settings
mode: train
experiment_name: # Name of the experiment

checkpoints: null # Checkpoints to resume training
saving_checkpoints: 10 # Save model every "saving_checkpoints" epochs
epochs: 200 # Number of training epochs
learning_rate: 0.002  # Paper: 0.001 for BV1, 0.002 for BV2
optimizer: AdamW  # Options: 'Adam', 'AdamW', 'SGD'

# Loss settings
criterion: Combined  # Options: L1 (paper), SIlog, Combined
l1_weight: 0.237
silog_weight: 0.637
silog_lambda: 0.869  # SIlog scale parameter

validation: True # Perform validation 
validation_iter: 2 # Evaluate model on validation every "validation_iter" epochs

num_threads: 4
batch_size: 256  # Paper: 128 for BV1, 256 for BV2
shuffle: True # If "True" shuffle train set and val set